export const LOAD_SEARCH = 'LOAD_SEARCH';
export const RESET_SEARCH = 'RESET_SEARCH';

export const CREATE_URL = 'CREATE_URL';
export const RESPONSE_YOUTUBE = 'RESPONSE_YOUTUBE';
export const CREATE_VIDEO_LIST = 'CREATE_VIDEO_LIST';
